apiVersion: v1
kind: DeploymentConfig
metadata:
  name: vault-example
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: vault-example
      annotations:
        vaultproject.io/policies: default
        vaultproject.io/ttl: "24h"
        pod.beta.kubernetes.io/init-containers: '[
          {
            "name": "vault-init",
            "image": "raffaelespazzoli/credscontroller:0.0.1",
            "args" : ["initcreds"],
            "imagePullPolicy": "Always",
            "ports" : [
              {
                "containerPort" : 18080,
                "name" : "init-port"
               }
            ],
            "env": [
              {
                "name": "POD_NAME",
                "valueFrom": {"fieldRef": {"fieldPath": "metadata.name"}}
              },
              {
                "name": "POD_IP",
                "valueFrom": {"fieldRef": {"fieldPath": "status.podIP"}}
              },              
              {
                "name": "POD_NAMESPACE",
                "valueFrom": {"fieldRef": {"fieldPath": "metadata.namespace"}}
              },
              {
                "name": "VAULT_CACERT",
                "value": "/var/run/secrets/kubernetes.io/serviceaccount/service-ca.crt"
              },                                           
              {
                "name": "VAULT_ADDR",
                "value": "https://vault.vault-controller.svc.cluster.local:8200"
              },
              {
                "name": "VAULT_CONTROLLER_ADDR",
                "value": "https://vault-controller.vault-controller.svc.cluster.local:8080"
              },
              {
                "name": "VAULT_CONTROLLER_CACERT",
                "value": "/var/run/secrets/kubernetes.io/serviceaccount/service-ca.crt"
              },
              {
                "name": "VAULT_INIT_PORT",
                "value": "18080"
              },
              {
                "name": "LOG_LEVEL",
                "value": "debug"
              }                             
            ],
            "volumeMounts": [
              {
                "name": "vault-token",
                "mountPath": "/var/run/secrets/vaultproject.io"
              }
            ]
          }
        ]'
    spec:
      containers:
        - name: vault-example
          image: "kelseyhightower/vault-example:0.0.1"
          imagePullPolicy: Always
          env:
            - name: "VAULT_CACERT"
              value: "/var/run/secrets/kubernetes.io/serviceaccount/service-ca.crt"              
            - name: "VAULT_ADDR"
              value: "https://vault.vault-controller.svc.cluster.local:8200"                            
          volumeMounts:
            - name: vault-token
              mountPath: "/var/run/secrets/vaultproject.io"
      volumes:
        - name: vault-token
          emptyDir:
            medium: Memory
